name: Gitbook CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
    - name: Run Install Calibre
      run: |
        sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1
      with:
        node-version: '8.x'
    - name: Run Install gitbook
      run: |
        node -v
        npm -v
        pwd
        ls -al
        sudo npm -g install gitbook-cli
        sh clean-md.sh
 
